### ISSUE TITLE
Jellyfish version 2.1.3

### ISSUE THREAD

**Issue by dence** [PhKoch/RepARK#1]
Hi, has anyone tested RepARK with jellyfish version 2.1.3?

**Comment by PhKoch** [comment]
Hi dence,
Sorry for the late response.
We are currently using jellyfish 2.1.4 and discovered no problems with the combination of RepARK & jellyfish.
The latest version of jellyfish (2.2.0) was not yet tested at our site, but as there is no relevant change in functionality documented in the ChangeLog, I expect no problems.
